# Generated by Django 3.0.3 on 2020-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hindi', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
