# Generated by Django 3.0.3 on 2020-02-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='cons_false_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='total_false_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
