# Generated by Django 3.0.3 on 2020-02-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0002_auto_20200216_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='notes',
            field=models.CharField(default='', max_length=300),
        ),
    ]
