# Generated by Django 3.0.3 on 2020-02-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0006_auto_20200218_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
