# Generated by Django 3.0.3 on 2020-02-18 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0007_dictionary_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.CharField(max_length=300)),
                ('vocab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocabs.Dictionary')),
            ],
        ),
    ]
