# Generated by Django 3.0.3 on 2020-02-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0008_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='total_false_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
