# Generated by Django 3.0.3 on 2020-04-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabs', '0009_dictionary_total_false_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='last_attempt',
            field=models.CharField(default='First attempt', max_length=50),
        ),
    ]
